# ****** Important note ******
# Remove unexpected backslashes from source csv file prior to running this script

import csv
import json
import sys
from collections import defaultdict

def build_trial(row):
    return {
        "item": row["Item"],
        "condition": row["Condition"],
        "question": row["Question"],
        "trial_id": f"{row['Item']}_{row['Condition']}"
    }

def convert(csv_path, output_path="stims.js"):
    items_by_id = defaultdict(list)

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            items_by_id[row["Item"]].append(build_trial(row))

    items = [
        {
            "item_id": item_id,
            "conditions": conditions
        }
        for item_id, conditions in sorted(items_by_id.items())
    ]

    js = "// Auto-generated by csv_to_stims.py — do not edit by hand\n\n"
    js += "var items = " + json.dumps(items, indent=2) + ";\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Written to {output_path}")
    print(f"  {len(items_by_id)} items ({sum(len(v) for v in items_by_id.values())} rows)")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python csv_to_stims.py data.csv [output.js]")
        sys.exit(1)

    csv_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "stims.js"
    convert(csv_path, output_path)
